vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /users_images
            upload_destination: '%kernel.project_dir%/public/users_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer