api_login_check:
    path: /api/login_check
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
#getproduct:
 #   path: /api/product/byName/
#test:
 #   path: /test
  #  controller: App\test\testController::index
